import { db } from "./index";
import { resources } from "./schema";
import * as dotenv from "dotenv";
dotenv.config();

async function seed() {
  console.log("Seeding resources...");

  await db.insert(resources).values([
    {
      name:         "Silang Rural Health Unit",
      organization: "LGU Silang",
      category:     "health",
      address:      "Barangay Biga, Silang, Cavite",
      barangay:     "Biga",
      city:         "Silang",
      province:     "Cavite",
      phone:        "(046) 686-0019",
      hours:        "Monday–Friday, 8:00 AM – 5:00 PM",
      cost:         "free",
      description:  "Free consultations, vaccines, and basic medicine for Silang residents.",
      lat:          "14.2301",
      lng:          "120.9758",
      status:       "active",
      verified:     true,
    },
    {
      name:         "Ospital ng Silang",
      organization: "LGU Silang",
      category:     "health",
      address:      "Poblacion, Silang, Cavite",
      barangay:     "Poblacion",
      city:         "Silang",
      province:     "Cavite",
      phone:        "(046) 686-1234",
      hours:        "Open 24 hours, 7 days a week",
      cost:         "free",
      description:  "Community hospital serving Silang and nearby towns.",
      lat:          "14.2265",
      lng:          "120.9741",
      status:       "active",
      verified:     true,
    },
    {
      name:         "PESO Livelihood Office",
      organization: "Municipality of Silang",
      category:     "livelihood",
      address:      "Municipal Hall, Silang, Cavite",
      barangay:     "Poblacion",
      city:         "Silang",
      province:     "Cavite",
      phone:        "(046) 686-5678",
      hours:        "Monday–Thursday, 8:00 AM – 4:00 PM",
      cost:         "free",
      description:  "Job placement, livelihood programs, and skills training for residents.",
      lat:          "14.2250",
      lng:          "120.9755",
      status:       "active",
      verified:     true,
    },
    {
      name:         "MSWD – Social Welfare Office",
      organization: "Municipality of Silang",
      category:     "food_relief",
      address:      "Municipal Hall, Silang, Cavite",
      barangay:     "Poblacion",
      city:         "Silang",
      province:     "Cavite",
      phone:        "(046) 686-9012",
      hours:        "Monday–Friday, 8:00 AM – 5:00 PM",
      cost:         "free",
      description:  "Ayuda, relief goods, and social protection programs for those in need.",
      lat:          "14.2255",
      lng:          "120.9748",
      status:       "active",
      verified:     true,
    },
    {
      name:         "PAO – Public Attorney's Office",
      organization: "Department of Justice",
      category:     "legal_aid",
      address:      "Imus, Cavite (covers Silang)",
      barangay:     null,
      city:         "Imus",
      province:     "Cavite",
      phone:        "(046) 471-3456",
      hours:        "Monday–Friday, 8:00 AM – 5:00 PM",
      cost:         "free",
      description:  "Free legal representation and consultation for those who cannot afford a lawyer.",
      lat:          "14.2290",
      lng:          "120.9720",
      status:       "active",
      verified:     true,
    },
    {
      name:         "In Touch Community Services",
      organization: "In Touch Community Services, Inc.",
      category:     "mental_health",
      address:      "Online / Hotline – Available nationwide",
      barangay:     null,
      city:         "Silang",
      province:     "Cavite",
      phone:        "0917-800-1123",
      hours:        "Open 24 hours, 7 days a week",
      cost:         "free",
      description:  "Free and confidential mental health support hotline. Talk to a counselor anytime.",
      lat:          "14.2273",
      lng:          "120.9741",
      status:       "active",
      verified:     true,
    },
    {
      name:         "Silang Birthing Home",
      organization: "LGU Silang",
      category:     "health",
      address:      "Barangay San Miguel, Silang, Cavite",
      barangay:     "San Miguel",
      city:         "Silang",
      province:     "Cavite",
      phone:        "(046) 686-2233",
      hours:        "Monday–Friday, 8:00 AM – 5:00 PM",
      cost:         "free",
      description:  "Maternal care, prenatal checkups, and basic birthing services for residents.",
      lat:          "14.2281",
      lng:          "120.9812",
      status:       "active",
      verified:     true,
    },
    {
      name:         "Cavite Public Attorney's Office",
      organization: "Public Attorney's Office",
      category:     "legal_aid",
      address:      "Cavite Provincial Capitol, Trece Martires, Cavite",
      barangay:     "Capitol Site",
      city:         "Trece Martires",
      province:     "Cavite",
      phone:        "(046) 419-1111",
      hours:        "Monday–Friday, 8:00 AM – 5:00 PM",
      cost:         "free",
      description:  "Free legal consultation and assistance for qualified individuals.",
      lat:          "14.2818",
      lng:          "120.8660",
      status:       "active",
      verified:     true,
    },
    {
      name:         "Silang Food Assistance Program",
      organization: "Municipality of Silang",
      category:     "food_relief",
      address:      "Municipal Hall, Silang, Cavite",
      barangay:     "Poblacion",
      city:         "Silang",
      province:     "Cavite",
      phone:        "(046) 686-1000",
      hours:        "Monday–Friday, 8:00 AM – 5:00 PM",
      cost:         "free",
      description:  "Food packs and emergency food assistance for qualified families.",
      lat:          "14.2252",
      lng:          "120.9750",
      status:       "active",
      verified:     true,
    },
    {
      name:         "Silang Skills Training Center",
      organization: "TESDA / LGU Silang",
      category:     "livelihood",
      address:      "Barangay Tubuan, Silang, Cavite",
      barangay:     "Tubuan",
      city:         "Silang",
      province:     "Cavite",
      phone:        "(046) 686-3344",
      hours:        "Monday–Friday, 8:00 AM – 5:00 PM",
      cost:         "free",
      description:  "Skills training and livelihood programs for residents seeking employment or income opportunities.",
      lat:          "14.2189",
      lng:          "120.9821",
      status:       "active",
      verified:     true,
    },
    {
      name:         "Silang Community Learning Center",
      organization: "Department of Education",
      category:     "education",
      address:      "Barangay Bucal, Silang, Cavite",
      barangay:     "Bucal",
      city:         "Silang",
      province:     "Cavite",
      phone:        "(046) 686-4455",
      hours:        "Monday–Friday, 8:00 AM – 4:00 PM",
      cost:         "free",
      description:  "Free learning support, literacy programs, and alternative education services for children and adults.",
      lat:          "14.2352",
      lng:          "120.9688",
      status:       "active",
      verified:     true,
    },

    {
      name:         "Silang Educational Assistance Office",
      organization: "Municipality of Silang",
      category:     "education",
      address:      "Municipal Hall, Silang, Cavite",
      barangay:     "Poblacion",
      city:         "Silang",
      province:     "Cavite",
      phone:        "(046) 686-7788",
      hours:        "Monday–Friday, 8:00 AM – 5:00 PM",
      cost:         "free",
      description:  "Educational assistance and scholarship information for qualified students and families.",
      lat:          "14.2249",
      lng:          "120.9753",
      status:       "active",
      verified:     true,
    },
  ]).onConflictDoNothing();

  console.log("Seeding complete.");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
